### ISSUE TITLE
Hologram Planting Plot

### ISSUE THREAD

**Issue by s0ulska** [42MonthsAfter/Public#2]
couple of days ago, I found some weed seeds. I got lime and a shovel and created a farming plot on the ground. upon digging the plot with the shovel, a hologram plot appeared. it literally said hologram when you put the cursor on it. I then opened my pack of weed seeds and there were only 2 in the pack. I planted them and nothing ever grew... it took the seed and i fertilized and watered and nothing came up. 

so question is...  can you only grow on premade garden pots and is it typical to get random number off seeds?

**Comment by BnYrB** [comment]
This should be fixed! There was a conflict between More Doors and BB+, so we removed more doors from our server specific mod. 

This means that building fortifications and BB+ are the only ways to block off doors now. 

Let me know if you have any issues.
