### ISSUE TITLE
Went to go access our quartermaster 

### ISSUE THREAD

**Issue by Demonking42** [42MonthsAfter/Public#3]
There's no menu to our quartermaster at all cant see anything to sell or by 
![16526525042567594844449884600216](https://user-images.githubusercontent.com/105258586/168495922-2dc30e03-5a44-4a4c-b1e2-52e9137542cf.jpg)

**Comment by BnYrB** [comment]
should be fixed! Was an issue with all the traders, shouldn't have touched the db, let me know if you have anything missing
