### ISSUE TITLE
the holler no longer safe zone?

### ISSUE THREAD

**Issue by s0ulska** [42MonthsAfter/Public#4]
able to shoot and cause damage to players inside holler.

**Comment by BnYrB** [comment]
Were you inside the holler or outside of the safe zone shooting in?

Was the person who you were shooting at get hit and hurt?

This should be a safe zone, I'm unable to raise my gun in the Holler now now so the more details the better.

**Comment by s0ulska** [comment]
Able to ADS and shoot since I put in the issue ticket. My buddy and I noticed that you don't get the "welcome" to the holler message. We wondered if we could take damage, so he shot me in the foot and I took damage.

**Comment by BnYrB** [comment]
This should be fixed!
