### ISSUE TITLE
storage problems in holler

### ISSUE THREAD

**Issue by s0ulska** [42MonthsAfter/Public#7]
cannot put either solo locker or vanilla storage box in shack. shows placement but will not assemble.

**Comment by BnYrB** [comment]
There is a no-build put into the holler as it makes it so no one can raid another cabin or cut off the lock. The cabins are meant to be jumping off points while you get your base situated. I can add some more storage, but please keep in mind the more storage the larger the impacts on performance. 

Let me know what cabin you are in and how much storage you and I'll drop it off.
